require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  DisabledByDefault: true
  Exclude:
    - "gems/**/*"
  NewCops: enable

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

# セミコロンを使わない
Semicolon:
  AllowAsExpressionSeparator: false
# インデントに関する指摘を有効にする
Layout/IndentationWidth:
  Enabled: true
Layout/IndentationConsistency:
  Enabled: true
# 不要なreturn句を使わない
Style/RedundantReturn:
  Enabled: true
